name: CI

on:
  push:
    branches:
    - "**"
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: angr/ci-settings/.github/workflows/angr-ci.yml@master
    with:
       container_image: angr/ci:jammy
